const siteConfig = {
  name: "Tivat Car Hire",
  tagline: "Drive from Porto Montenegro",
  domain: "tivatcarhire.com",
  phone: "",
  email: "info@tivatcarhire.com",
  address: "Tivat, Montenegro",

  hero: {
    headline: "Car Hire in Tivat",
    subheadline: "Pick up at Tivat Airport arrivals and drive the entire Montenegrin coast. Porto Montenegro, Kotor, and the Bay are minutes away.",
    image: "/img/hero-tivat.webp",
  },

  cars: [
    {
      id: 1,
      slug: "vw-polo",
      name: "VW Polo",
      category: "Economy",
      price: 25,
      image: "/img/pexels-1035108.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Air Conditioning", "Bluetooth Audio", "USB Charging", "Central Locking"],
      popular: false,
    },
    {
      id: 2,
      slug: "skoda-octavia",
      name: "Skoda Octavia",
      category: "Mid-Size",
      price: 35,
      image: "/img/pexels-116675.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 4,
      ac: true,
      features: ["Automatic Transmission", "Cruise Control", "Parking Sensors", "Large Boot"],
      popular: true,
    },
    {
      id: 3,
      slug: "toyota-corolla",
      name: "Toyota Corolla",
      category: "Mid-Size",
      price: 38,
      image: "/img/pexels-170811.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Hybrid",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Hybrid Engine", "Reversing Camera", "Apple CarPlay", "Keyless Start"],
      popular: false,
    },
    {
      id: 4,
      slug: "mercedes-c-class",
      name: "Mercedes C-Class",
      category: "Premium",
      price: 65,
      image: "/img/pexels-120049.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Leather Seats", "Navigation System", "Premium Sound", "Heated Seats"],
      popular: true,
    },
    {
      id: 5,
      slug: "jeep-renegade",
      name: "Jeep Renegade",
      category: "SUV",
      price: 55,
      image: "/img/pexels-1638459.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["4x4 Drive", "Hill Descent Control", "Roof Rails", "Off-Road Mode"],
      popular: false,
    },
    {
      id: 6,
      slug: "bmw-x3",
      name: "BMW X3",
      category: "Premium SUV",
      price: 85,
      image: "/img/pexels-892522.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 4,
      ac: true,
      features: ["Panoramic Roof", "Adaptive Cruise", "360 Camera", "Sport Mode"],
      popular: false,
    },
    {
      id: 7,
      slug: "fiat-500",
      name: "Fiat 500",
      category: "City",
      price: 20,
      image: "/img/pexels-1007410.jpg",
      seats: 4,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 2,
      luggage: 1,
      ac: true,
      features: ["Compact Size", "Easy Parking", "Sunroof", "Bluetooth"],
      popular: false,
    },
    {
      id: 8,
      slug: "vw-transporter",
      name: "VW Transporter",
      category: "Van",
      price: 70,
      image: "/img/pexels-2533092.jpg",
      seats: 9,
      transmission: "Manual",
      fuel: "Diesel",
      doors: 4,
      luggage: 6,
      ac: true,
      features: ["9 Seats", "Airport Shuttle Ready", "Sliding Doors", "Ample Storage"],
      popular: false,
    },
  ],

  features: [
    { icon: "map-pin", title: "40-Metre Pickup", description: "40 metres from the terminal exit to your car. No shuttle, no bus — walk straight out of baggage reclaim and into the short-stay car park." },
    { icon: "shield-check", title: "Full Insurance Included", description: "CDW and theft protection on every booking. Upgrade to zero-excess cover before you tackle the Vrmac tunnel or the bay road curves toward Herceg Novi." },
    { icon: "clock", title: "24/7 Roadside Line", description: "Flight delayed three hours? We adjust, no charge. Our roadside number reaches a local mechanic within 30 minutes, any hour of the day." },
    { icon: "ban", title: "Transparent Pricing", description: "VAT, mileage, airport surcharge, equipment kit — everything is folded into the figure on screen. The checkout total is the total you pay at pickup, nothing added at the desk." },
    { icon: "refresh-cw", title: "Free Cancellation", description: "Airline schedule changed or flight cancelled? Cancel up to 24 hours before pickup at no cost. No fees when carriers rearrange summer or winter schedules." },
    { icon: "globe", title: "Cross-Border Ready", description: "Green Card paperwork prepared at booking. Dubrovnik Airport is 90 km up the coast; the Croatian border crossing at Debeli Brijeg is 40 km. Documents will be in the glovebox." },
  ],

  testimonials: [
    { name: "Lars Eriksen", location: "Copenhagen, Denmark", text: "Business trip, tight schedule. Bags off the belt, car was in the short-stay lot across the road, and I was at Porto Montenegro for my meeting inside 20 minutes of landing. The speed of pickup at TIV is hard to beat.", rating: 5, avatar: "/img/avatar-1.webp" },
    { name: "Marta & Pau", location: "Barcelona, Spain", text: "We took the Verige ferry across from Kamenari and had lunch on the Lustica peninsula the same afternoon we landed. The agent mentioned the ferry shortcut at pickup — saved us 40 minutes on the bay road. Perfect tip.", rating: 5, avatar: "/img/avatar-2.webp" },
    { name: "Tomasz & Agnieszka", location: "Warsaw, Poland", text: "Ryanair into Tivat, car ready in the car park, kids in their seats, and we were through the Vrmac tunnel and parking outside Kotor's walls before the hour was up. The tunnel made such a difference over the bay road.", rating: 5, avatar: "/img/avatar-3.webp" },
  ],

  faq: [
    { q: "What documents do I need at TIV pickup?", a: "A driving licence with Latin-script details, a passport, and a physical credit card in the main driver's name. If your licence uses only non-Latin characters, bring an International Driving Permit. Electronic licences and photocopies are not accepted." },
    { q: "Can I drive the rental car to Croatia or Albania?", a: "Yes. Notify the rental company at booking so they prepare the Green Card insurance certificate. Cross-border travel to Croatia, Bosnia, Albania, Serbia, and Kosovo is permitted — documents will be in the glovebox when you collect at TIV." },
    { q: "Is there a minimum age to rent?", a: "Age and experience requirements depend on the vehicle category. Economy cars typically require 21+, premium vehicles 25+. These details appear during the search before you commit to a booking." },
    { q: "What is included in the rental price?", a: "CDW and theft protection, VAT, an equipment kit (first-aid box, warning triangle, reflective vest), and a transparent fuel policy. Mileage terms vary by vehicle — some are unlimited, others capped at a daily kilometre allowance shown on the listing." },
    { q: "How does TIV airport pickup work?", a: "Tivat is a single-terminal airport. After you clear baggage reclaim, walk out the terminal exit and cross to the short-stay car park — roughly 40 metres. Our agent meets you there with the keys and paperwork. Total time from bag belt to driving: about 10 minutes." },
    { q: "Can I drop off at a different location?", a: "Yes. One-way rentals are supported across 28+ towns in Montenegro. Pick up at TIV and drop off in Budva, Kotor, Podgorica, or across the border in Dubrovnik. Select different pickup and drop-off points during booking." },
    { q: "What is the cancellation policy?", a: "Free cancellation up to 7 days before the rental start date for standard vehicles, up to 30 days for premium and convertible categories. A 6% payment processing fee applies to all refunds." },
    { q: "Is a deposit required?", a: "Deposit amounts vary by vehicle group — some economy cars require no deposit at all. When a deposit applies, it must be on a physical credit card in the main driver's name and is refunded on return of the vehicle." },
    { q: "Where is the nearest fuel station to TIV?", a: "There is a Jugopetrol station 800 metres from the airport exit on the main road toward Tivat town, and a Petrol station in Radanovici on the Budva road. Both accept card and cash payment." },
    { q: "Are there any hidden fees?", a: "No. Taxes, airport surcharge, equipment kit — all included. The price at checkout is the price you pay at pickup. We do not add fees at the desk." },
    { q: "How much do I pay upfront?", a: "Only 15–20% of the total is charged at booking to secure the car. The balance is paid directly to the rental agent at the airport when you collect." },
    { q: "Can I rent without a credit card?", a: "Some vehicles are available without a credit card — these are clearly marked with a card-free badge in the search results. Filter for them during your search." },
  ],

  locations: [
    { name: "Tivat Airport", tag: "Most Popular" },
    { name: "Porto Montenegro", tag: "Marina" },
    { name: "Tivat Town", tag: "" },
    { name: "Kotor", tag: "" },
    { name: "Budva", tag: "" },
    { name: "Herceg Novi", tag: "" },
  ],

  destinations: [
    {
      name: "Tivat Airport",
      slug: "tivat-airport",
      tag: "Most Popular",
      desc: "Collect your car at arrivals — 10 minutes to driving.",
      image: "/img/tivat-airport.webp",
    },
    {
      name: "Kotor",
      slug: "kotor",
      tag: "20 min",
      desc: "UNESCO walled town on the Bay of Kotor.",
      image: "/img/kotor-nearby.webp",
    },
    {
      name: "Budva",
      slug: "budva",
      tag: "30 min",
      desc: "Riviera beaches and the old town walls.",
      image: "/img/budva-nearby.webp",
    },
    {
      name: "Herceg Novi",
      slug: "dubrovnik-airport",
      tag: "35 min",
      desc: "Gateway town near the Croatian border.",
      image: "/img/herceg-novi.webp",
    },
    {
      name: "Perast",
      slug: "perast",
      tag: "25 min",
      desc: "Baroque village and Our Lady of the Rocks.",
      image: "/img/boka-bay.webp",
    },
    {
      name: "Tivat",
      slug: "tivat",
      tag: "Porto Montenegro",
      desc: "Luxury marina, waterfront dining, Boka Bay.",
      image: "/img/porto-montenegro.webp",
    },
    {
      name: "Podgorica",
      slug: "podgorica",
      tag: "Capital City",
      desc: "Montenegro's capital — culture and commerce.",
      image: "/img/podgorica-city.webp",
    },
    {
      name: "Podgorica Airport",
      slug: "podgorica-airport",
      tag: "Capital Hub",
      desc: "Montenegro's main international airport.",
      image: "/img/podgorica-airport.webp",
    },
  ],
};

export default siteConfig;
