const siteConfig = {
  name: "Tivat Car Hire",
  tagline: "Drive from Porto Montenegro",
  domain: "tivatcarhire.com",
  phone: "",
  email: "info@tivatcarhire.com",
  address: "Tabacina BB, Kotor, 85330",

  hero: {
    headline: "Car Hire in Tivat",
    subheadline: "Pick up at Tivat Airport arrivals and drive the entire Montenegrin coast. Porto Montenegro, Kotor, and the Bay are minutes away.",
    image: "/img/hero-tivat.webp",
  },

  cars: [
    {
      id: 1,
      slug: "renault-clio",
      typeGroup: "economy",
      name: "Renault Clio",
      category: "Economy",
      tagline: "The marina-friendly default, compact, cheap to fuel, slots into Porto Montenegro's short bays",
      lede: "Most rented small car in Tivat. Five doors, a 391-litre boot, and the sort of turning circle that matters on Pine Walk.",
      price: 28,
      image: "/img/fleet/renault-clio.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Bluetooth Audio","USB Charging","Central Locking","Touchscreen Display"],
      details: {
        engine: "1.0 TCe 3-cyl turbo petrol",
        power: "100 hp",
        consumption: "5.3 L/100 km",
        bootSize: "391 L",
        length: "4,050 mm",
        topSpeed: "188 km/h",
        acceleration: "11.8s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: true,
      bestFor: ["Marina-based couples","Short-stay Tivat trips","First-time Boka visitors"],
      suitability: "Two travellers with cabin bags staying around Porto Montenegro or Tivat town, taking the odd day out to Kotor or Perast. The default workhorse of the Tivat rental fleet.",
      regional: "Fits the metered bays along Šetalište Pet Danica and the tight angled spots behind the Tivat bus station. Comfortable on the Vrmac tunnel run to Kotor and the new Sozina road toward Budva without feeling outclassed on longer legs.",
    },
    {
      id: 2,
      slug: "vw-polo",
      typeGroup: "economy",
      name: "VW Polo",
      category: "Economy",
      tagline: "Solid German hatch that takes the Lepetane ferry queue in its stride",
      lede: "Small enough for Porto Montenegro's waterfront bays, serious enough to make the Lustica run feel like a larger car.",
      price: 25,
      image: "/img/fleet/vw-polo.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Air Conditioning", "Bluetooth Audio", "USB Charging", "Central Locking"],
      details: {
        engine: "1.0 L TSI 3-cyl turbo petrol",
        power: "95 hp",
        consumption: "5.2 L/100 km",
        bootSize: "351 L",
        length: "4,074 mm",
        topSpeed: "187 km/h",
        acceleration: "10.8s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Marina apartment stays","Couples and friends","Porto Montenegro shoppers"],
      suitability: "Two travellers anchored in Tivat town or at a Porto Montenegro apartment, mixing marina dinners with short day trips to Kotor, Perast and the Luštica coast road.",
      regional: "Slots into the narrow angled bays behind the Tivat Main Square without drama, holds 120 km/h on the Sozina dual-carriageway toward Budva, and the 95 hp triple is unbothered by the short climb from the Lepetane ferry ramp. Quieter at motorway pace than a Fiat 500 and cheaper to fuel than the mid-size diesels.",
    },
    {
      id: 3,
      slug: "peugeot-308",
      typeGroup: "midsize",
      name: "Peugeot 308",
      category: "Mid-Size",
      tagline: "Mid-size diesel auto, the calm cruiser for the Podgorica and Dubrovnik runs",
      lede: "Quiet BlueHDi diesel, 412-litre boot, 8-speed auto, the car to pick when Tivat is just the base, not the destination.",
      price: 38,
      image: "/img/fleet/peugeot-308.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Automatic Transmission","Adaptive Cruise","Dual-Zone Climate","Large Boot"],
      details: {
        engine: "1.5 BlueHDi 4-cyl diesel",
        power: "130 hp",
        consumption: "4.4 L/100 km",
        bootSize: "412 L (1,309 L seats folded)",
        length: "4,367 mm",
        topSpeed: "206 km/h",
        acceleration: "10.1s (0–100 km/h)",
        driveType: "Front-wheel drive, 8-spd auto",
      },
      popular: true,
      bestFor: ["Long-stay couples","Cross-border travellers","Families of four"],
      suitability: "Four adults with real luggage, or a family doing the Tivat–Kotor–Budva–Podgorica circuit over a week. Auto + diesel + cruise is the combination for longer Tivat-based itineraries.",
      regional: "Cruises the Sozina road to Podgorica and the coast run to Dubrovnik airport without fuss, holds the family kit for Plavi Horizonti beach days, and handles the Lepetane ferry queue without cooking its clutch. The length shows in Porto Montenegro's tightest bays, use the paid marina lots.",
    },
    {
      id: 4,
      slug: "renault-megane",
      typeGroup: "midsize",
      name: "Renault Megane",
      category: "Mid-Size",
      tagline: "Biggest boot in the mid-size class, the beach-kit and family-day-trip default",
      lede: "434-litre boot, quiet diesel, soft long-distance ride, the family-friendly pick for Lustica day trips.",
      price: 36,
      image: "/img/fleet/renault-megane.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Large Boot","Bluetooth Audio","Cruise Control","Parking Sensors"],
      details: {
        engine: "1.5 Blue dCi 4-cyl diesel",
        power: "115 hp",
        consumption: "4.3 L/100 km",
        bootSize: "434 L",
        length: "4,360 mm",
        topSpeed: "195 km/h",
        acceleration: "11.1s (0–100 km/h)",
        driveType: "Front-wheel drive, 6-spd manual",
      },
      popular: false,
      bestFor: ["Families with children","Beach-kit-heavy travellers","Plavi Horizonti regulars"],
      suitability: "A family of four with pushchair, parasol and beach bag for Luštica day trips, or a couple on an extended bay tour with luggage for two cross-border detours.",
      regional: "The 434-litre boot swallows a cool-box, pushchair and beach gear for a Plavi Horizonti morning, with room left for a grocery run from Voli on the way home. Manual diesel is thrifty on the drive across to Herceg Novi via the Lepetane ferry and back through the Vrmac tunnel.",
    },
    {
      id: 5,
      slug: "fiat-500",
      typeGroup: "economy",
      name: "Fiat 500",
      category: "City",
      tagline: "Tiny city car for the photogenic laps of Pine Walk and Porto Montenegro",
      lede: "Parks where nothing else fits, the pick for a Tivat week built around marina coffees, Pine Walk strolls and photo stops.",
      price: 20,
      image: "/img/fleet/fiat-500.jpg",
      seats: 4,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 2,
      luggage: 1,
      ac: true,
      features: ["Compact Size", "Easy Parking", "Sunroof", "Bluetooth"],
      details: {
        engine: "1.0 L mild-hybrid petrol",
        power: "70 hp",
        consumption: "5.4 L/100 km",
        bootSize: "185 L",
        length: "3,571 mm",
        topSpeed: "167 km/h",
        acceleration: "13.8s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Solo travellers","Couples on short stays","Marina photographers"],
      suitability: "One or two travellers with cabin bags spending most of the week at Porto Montenegro or Tivat town, using the car for slow Luštica laps, Donja Lastva lunches and Pine Walk photo runs rather than long-distance pushes.",
      regional: "The only car that genuinely fits the angled bays inside the Porto Montenegro complex next to the yacht pontoons, and parks free of charge on the residential grid above the Tivat Main Square. Sunroof open is a requirement on the Luštica coast road to Krašići. Skip it for the Dubrovnik airport run, it is happiest below 80 km/h on the bay road.",
    },
    {
      id: 6,
      slug: "vw-golf",
      typeGroup: "midsize",
      name: "VW Golf",
      category: "Mid-Size",
      tagline: "The DSG diesel benchmark, every Tivat journey done adequately, none brilliantly",
      lede: "Clio's agility plus 308's distance-eating refinement. The rational mid-size pick for mixed trips.",
      price: 42,
      image: "/img/fleet/vw-golf.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["DSG Automatic", "Adaptive Cruise", "Digital Cockpit", "Apple CarPlay"],
      details: {
        engine: "2.0 L TDI diesel (Mk8)",
        power: "150 hp",
        consumption: "4.3 L/100 km",
        bootSize: "381 L (1,237 L seats folded)",
        length: "4,287 mm",
        topSpeed: "223 km/h",
        acceleration: "8.4s (0–100 km/h)",
        driveType: "Front-wheel drive, 7-spd DSG auto",
      },
      popular: false,
      bestFor: ["Couples mixing marina and day trips","Quick Tivat airport transfers","Mixed coast and inland routes"],
      suitability: "Couples who want marina-town agility on the Tivat waterfront plus the long-distance refinement of a 308 for the occasional Dubrovnik or Budva push, without paying full mid-size prices.",
      regional: "Threads the Vrmac tunnel approach at composed speed, handles the Lepetane ferry ramp and bay road sensibly, and the DSG reads the Sozina motorway gradients so you don't have to. 4.3 L/100 km on the coastal cruise makes a week of Tivat-based touring genuinely cheap.",
    },
    {
      id: 7,
      slug: "toyota-yaris",
      typeGroup: "economy",
      name: "Toyota Yaris",
      category: "Economy",
      tagline: "Silent electric crawl past the superyachts, the marina hybrid",
      lede: "3.8 L/100 km real-world, near-silent below 30 km/h. The Tivat town car with almost no fuel cost.",
      price: 34,
      image: "/img/fleet/toyota-yaris.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Hybrid",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Hybrid Drivetrain","Reversing Camera","Apple CarPlay","Adaptive Cruise"],
      details: {
        engine: "1.5 VVT-i Hybrid petrol–electric",
        power: "116 hp combined",
        consumption: "3.8 L/100 km",
        bootSize: "286 L",
        length: "3,940 mm",
        topSpeed: "175 km/h",
        acceleration: "9.7s (0–100 km/h)",
        driveType: "Front-wheel drive (e-CVT)",
      },
      popular: true,
      bestFor: ["Fuel-conscious marina stays","Urban hops around Tivat","Quiet pre-dawn airport runs"],
      suitability: "Travellers whose Tivat week is mostly marina dinners, Pine Walk cycling, and short hops to the airport or Porto Montenegro, the hybrid pays for itself in savings against a Vrmac tunnel-and-back routine.",
      regional: "Pure-electric creep through Porto Montenegro's boat-yard streets at 6am, then the petrol wakes for the climb through the Vrmac tunnel toward Kotor. A week of marina-based exploring costs under €40 in fuel; don't pick it for heavy Durmitor climbs where battery drain hurts.",
    },
  ],

  features: [
    { icon: "map-pin", title: "40-Metre Pickup", description: "40 metres from the terminal exit to your car. No shuttle, no bus, walk straight out of baggage reclaim and into the short-stay car park." },
    { icon: "shield-check", title: "Full Insurance Included", description: "CDW and theft protection on every booking. Upgrade to zero-excess cover before you tackle the Vrmac tunnel or the bay road curves toward Herceg Novi." },
    { icon: "clock", title: "24/7 Roadside Line", description: "Flight delayed three hours? We adjust, no charge. Our roadside number reaches a local mechanic within 30 minutes, any hour of the day." },
    { icon: "ban", title: "Transparent Pricing", description: "VAT, mileage, airport surcharge, equipment kit, everything is folded into the figure on screen. The checkout total is the total you pay at pickup, nothing added at the desk." },
    { icon: "refresh-cw", title: "Free Cancellation", description: "Airline schedule changed or flight cancelled? Cancel up to 24 hours before pickup at no cost. No fees when carriers rearrange summer or winter schedules." },
    { icon: "globe", title: "Cross-Border Ready", description: "Green Card paperwork prepared at booking. Dubrovnik Airport is 90 km up the coast; the Croatian border crossing at Debeli Brijeg is 40 km. Documents will be in the glovebox." },
  ],

  testimonials: [
    { name: "Lars Eriksen", location: "Copenhagen, Denmark", text: "Business trip, tight schedule. Bags off the belt, car was in the short-stay lot across the road, and I was at Porto Montenegro for my meeting inside 20 minutes of landing. The speed of pickup at TIV is hard to beat.", rating: 5, avatar: "/img/avatar-1.webp" },
    { name: "Marta & Pau", location: "Barcelona, Spain", text: "We took the Verige ferry across from Kamenari and had lunch on the Lustica peninsula the same afternoon we landed. The agent mentioned the ferry shortcut at pickup, saved us 40 minutes on the bay road. Perfect tip.", rating: 5, avatar: "/img/avatar-2.webp" },
    { name: "Tomasz & Agnieszka", location: "Warsaw, Poland", text: "Ryanair into Tivat, car ready in the car park, kids in their seats, and we were through the Vrmac tunnel and parking outside Kotor's walls before the hour was up. The tunnel made such a difference over the bay road.", rating: 5, avatar: "/img/avatar-3.webp" },
  ],

  faq: [
    { q: "Can I drop off at a different location?", a: "Yes. One-way rentals are supported across 28+ towns in Montenegro. Pick up at TIV and drop off in Budva, Kotor, Podgorica, or across the border in Dubrovnik. Select different pickup and drop-off points during booking." },
    { q: "What documents do I need at TIV pickup?", a: "A driving licence with Latin-script details, a passport, and a physical credit card in the main driver's name. If your licence uses only non-Latin characters, bring an International Driving Permit. Electronic licences and photocopies are not accepted." },
    { q: "Can I drive the rental car to Croatia or Albania?", a: "Yes. Notify the rental company at booking so they prepare the Green Card insurance certificate. Cross-border travel to Croatia, Bosnia, Albania, Serbia, and Kosovo is permitted, documents will be in the glovebox when you collect at TIV." },
    { q: "Is there a minimum age to rent?", a: "Age and experience requirements depend on the vehicle category. Economy cars typically require 21+, premium vehicles 25+. These details appear during the search before you commit to a booking." },
    { q: "What is included in the rental price?", a: "CDW and theft protection, VAT, an equipment kit (first-aid box, warning triangle, reflective vest), and a transparent fuel policy. Mileage terms vary by vehicle, some are unlimited, others capped at a daily kilometre allowance shown on the listing." },
    { q: "How does TIV airport pickup work?", a: "Tivat is a single-terminal airport. After you clear baggage reclaim, walk out the terminal exit and cross to the short-stay car park, roughly 40 metres. Our agent meets you there with the keys and paperwork. Total time from bag belt to driving: about 10 minutes." },
    { q: "What is the cancellation policy?", a: "Free cancellation up to 7 days before the rental start date for standard vehicles, up to 30 days for premium and convertible categories. A 6% payment processing fee applies to all refunds." },
    { q: "Is a deposit required?", a: "Deposit amounts vary by vehicle group, some economy cars require no deposit at all. When a deposit applies, it must be on a physical credit card in the main driver's name and is refunded on return of the vehicle." },
    { q: "Where is the nearest fuel station to TIV?", a: "There is a Jugopetrol station 800 metres from the airport exit on the main road toward Tivat town, and a Petrol station in Radanovici on the Budva road. Both accept card and cash payment." },
    { q: "Are there any hidden fees?", a: "No. Taxes, airport surcharge, equipment kit, all included. The price at checkout is the price you pay at pickup. We do not add fees at the desk." },
    { q: "How much do I pay upfront?", a: "Only 15-20% of the total is charged at booking to secure the car. The balance is paid directly to the rental agent at the airport when you collect." },
    { q: "Can I rent without a credit card?", a: "Some vehicles are available without a credit card, these are clearly marked with a card-free badge in the search results. Filter for them during your search." },
  ],

  locations: [
    { name: "Tivat Airport", tag: "Most Popular" },
    { name: "Porto Montenegro", tag: "Marina" },
    { name: "Tivat Town", tag: "" },
    { name: "Kotor", tag: "" },
    { name: "Budva", tag: "" },
    { name: "Herceg Novi", tag: "" },
  ],

  destinations: [
    {
      name: "Tivat Airport",
      slug: "tivat-airport",
      tag: "Most Popular",
      desc: "Collect your car at arrivals, 10 minutes to driving.",
      image: "/img/tivat-airport.webp",
    },
    {
      name: "Kotor",
      slug: "kotor",
      tag: "20 min",
      desc: "walled town on the Bay of Kotor.",
      image: "/img/kotor-nearby.webp",
    },
    {
      name: "Budva",
      slug: "budva",
      tag: "30 min",
      desc: "Riviera beaches and the old town walls.",
      image: "/img/budva-nearby.webp",
    },
    {
      name: "Herceg Novi",
      slug: "dubrovnik-airport",
      tag: "35 min",
      desc: "Gateway town near the Croatian border.",
      image: "/img/herceg-novi.webp",
    },
    {
      name: "Perast",
      slug: "perast",
      tag: "25 min",
      desc: "Baroque village and Our Lady of the Rocks.",
      image: "/img/boka-bay.webp",
    },
    {
      name: "Tivat",
      slug: "tivat",
      tag: "Porto Montenegro",
      desc: "Luxury marina, waterfront dining, Boka Bay.",
      image: "/img/porto-montenegro.webp",
    },
    {
      name: "Podgorica",
      slug: "podgorica",
      tag: "Capital City",
      desc: "Montenegro's capital, culture and commerce.",
      image: "/img/podgorica-city.webp",
    },
    {
      name: "Podgorica Airport",
      slug: "podgorica-airport",
      tag: "Capital Hub",
      desc: "Montenegro's main international airport.",
      image: "/img/podgorica-airport.webp",
    },
  ],
};

export default siteConfig;
